### ISSUE TITLE
Style the Product Comparison Site

### ISSUE THREAD

**Issue by Berger101** [Berger101/product-comparison-site#16]
As a **user**, I want the **site to have a consistent and appealing design so that I have a good user experience.**

**Acceptance Criteria:**

- [ ] Consistent theme, colors, and typography are applied to the site.
- [ ] UI components are styled using CSS/SCSS.
- [ ] Styling is reviewed and refined for a polished look.
