### ISSUE TITLE
Favorite Action Feedback

### ISSUE THREAD

**Issue by Berger101** [Berger101/product-comparison-site#16]
**As a user**, I want to know when my **favorite action has been completed so that I understand if my interaction was successful.**

**Acceptance Criteria:**

- [ ] A success message is displayed when a product is successfully favorited.
- [x] A visual indicator, like a highlighted icon, shows when a product is favorited.
- [ ] A message confirms when a product is unfavorited.
