### ISSUE TITLE
Style the Product Comparison Site

### ISSUE THREAD

**Issue by Berger101** [Berger101/product-comparison-site#3]
As a **user**, I want the **site to have a consistent and appealing design so that I have a good user experience.**

**Acceptance Criteria:**

- [x] Consistent theme, colors, and typography are applied to the site.
- [x] UI components are styled using CSS/SCSS.
- [x] Styling is reviewed and refined for a polished look.
