### ISSUE TITLE
Develop Product Listing Page

### ISSUE THREAD

**Issue by Berger101** [Berger101/product-comparison-site#9]
As a **user**, I want to **see a list of products so that I can browse available products.**

**Acceptance Criteria:**

- [ ] Product listing page is created and displays products.
- [ ] Sorting and filtering options are available.
- [ ] Data is fetched from the backend API and displayed.
