### ISSUE TITLE
Develop Product Listing Page

### ISSUE THREAD

**Issue by Berger101** [Berger101/product-comparison-site#9]
As a **user**, I want to **see a list of products so that I can browse available products.**

**Acceptance Criteria:**

- [x] Product listing page is created and displays products.
- [x] Sorting and filtering options are available.
- [x] Data is fetched from the backend API and displayed.
